@startuml
class "Chemical Entity" as ChemicalEntity
class "Atom" as Atom
class "Chemical Substance" as ChemicalSubstance
class "Group" as Group
class "Molecular Entity" as MolecularEntity

Atom -up-> ChemicalEntity : is a
ChemicalSubstance -up-> ChemicalEntity : is a
Group -up-> ChemicalEntity : is a
MolecularEntity -up-> ChemicalEntity : is a
@enduml